config/routes.rb
Rails.application.routes.draw do
  root                        to: 'pages#index'
  get 'index',                to: 'pages#index'

  get '/about',               to: 'pages#about'
  get '/about_our_name',      to: 'pages#about_our_name'
  get '/contact',             to: 'pages#contact'
  get '/privacy',             to: 'pages#privacy'

  #Mailer
  get 'contact-us',           to: 'messages#new',         as: 'new_message'
  post 'contact-us',          to: 'messages#create',      as: 'create_message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body

  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      # redirect_to new_message_url, notice: "Message received, thanks!"
      redirect_to(root_path, notice: "Message has been sent, thanks!")
    else
      redirect_back(fallback_location: root_path, warning: "Your message could not be sent.")
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def about_our_name
  end

  def contact
    @message = Message.new
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_name
    @site_name = nil
    @site_name = @site_name || Rails.application.class.parent_name.titleize
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message
      end)
    end
    nil
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.haml
%footer.footer.footer_mst3k
  .space-50
  .container
    .row.vertical-align-child
      .col-md-3.margin-b-30
        .margin-b-20
          = link_to(image_tag('logo.png', class: 'logo-default header-logo'), root_path)
        %p
          Humble Daisy in a solution development company located in Ann Arbor, MI
      .col-md-2.margin-b-30
        %ul.list-unstyled
          %li
            = link_to('About', about_path)
          %li
            = link_to "Privacy Policy", privacy_path

      .col-md-5.margin-b-30
        %ul.list-inline.social

          %li.list-inline-item

            %a{:href => "https://twitter.com/humbledaisy",  target: '_blank', alt: 'Follow us on twitter'}
              %i.fa.fa-twitter

          %li.list-inline-item
            %a{:href => "http://lnkd.in/VuU9xY",  target: '_blank', alt: 'Check me out on LinkedIn'}
              %i.fa.fa-linkedin
          -# %li.list-inline-item
          -#   = mail_to("dschmura@humbledaisy.com", "", subject: "ManonaM", encode: :javascript, class: "fa fa-envelope fa-3x wow bounceIn connect_icons", "data-original-title" => "Send me an email, if you must.", rel: :tooltip, "data-placement" => :bottom)
          %li.list-inline-item
            = link_to( contact_url) do
              %i.fa.fa-envelope
      %span © Copyright 2016 - 2020

app/views/layouts/_header.html.haml
#preloader
  #preloader-inner
/ /preloader
/ back to top
%a.scrollToTop{:href => "#"}
  %i.fa.fa-arrow-up
/ back to top end
/ Static navbar
%nav.navbar.navbar-toggleable-md.navbar-light.fixed-top.navbar-transparent.shirnk.clearfix
  / Start Top Search
  .top-search.clearfix
    .container
      .input-group
        %span.input-group-addon
          %i.ion-search
        %input.form-control{:placeholder => "Search", :type => "text"}/
        %span.input-group-addon.close-search
          %i.ion-android-close
  / End Top Search
  .clearfix
  .container
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    -# = link_to('', root_path, class: 'navbar-brand')
    %a.navbar-brand{:href => "../"}

      -# %img.logo-default{:alt => "", :src => "assets/images/logo-light.png"}/
      -# %img.logo-scroll{:alt => "", :src => "assets/images/logo.png"}/
      = image_tag('logo.png', class: 'logo-default header-logo')
      = image_tag('logo-light.png', class: 'logo-scroll header-logo')
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          =link_to("Home", root_path, class: 'nav-link')
        %li.nav-item
          =link_to("Features", "#features-section", class: 'nav-link' )


        -# %li.nav-item
        -#   =link_to("Testamonials", "#testamonials", class: 'nav-link' )

        %li.nav-item.dropdown
          %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com", :role => ""}
            Showcase
          %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
            %li
              =link_to("Showcase Overview", "#showcase-web", class: 'nav-link' )
            %li
              =link_to("Web Showcase", "#showcase-web", class: 'dropdown-item' )

            %li
              =link_to("Showcase SonicPics", "#showcase-sonicpics", class: 'dropdown-item' )
            %li
              =link_to("Showcase ProfCast", "#showcase-profcast", class: 'dropdown-item' )
        %li.nav-item
          |
        %li.nav-item
          =link_to("About", about_path, class: 'nav-link')
        %li.nav-item
          =link_to("Contact", contact_url, class: 'nav-link' )




    -#     %li.nav-item
    -#       %a.btn.btn-rounded.btn-primary.nav-link{:href => "#"} Free Trail
    -# / Start search Navigation
    -# .search-nav.float-right
    -#   %a{:href => "javascript:void(0)"}
    -#     %i.fa.fa-search
/ navbar end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %title Humbledaisy Website
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{:class => controller.controller_name, "data-spy" => "scroll"}
    = render 'layouts/header'
    .content#content
    = yield
    = render 'layouts/footer'

app/views/message/contact_us.html.haml
-# %h1= class_name + "#" + @action

-# %p
-#   = @greeting + ", find me in app/views/message/contact_us.html.haml"
= @body

app/views/message/contact_us.text.haml
-# Message#contact_us

-# = @greeting + ", find me in app/views/message/contact_us.text.haml"

= @body

app/views/messages/new.html.haml
.container
  .row
    %h1 Send us a message
  .row
  %hr
    = form_for @message, url: create_message_url do |f|
      = notice
      = @message.errors.full_messages.join(', ')
      = f.text_field :name, placeholder: 'name'
      = f.email_field :email, placeholder: 'email'
      = f.text_area :body, placeholder: 'body'
      = f.submit 'Send'

app/views/pages/_features_section.html.haml
%section.features-section#features-section.border-bottom
  .container
    .row
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.fa.fa-crop
          %h4.text-capitalize Design
          %p
            By clearly understanding the goals of the project, I design web applications that are designed to accomplish those goals. Careful planning improves the effectiveness of the application while minimizing the cost of revisions as new enhancements are added in the future.
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.fa.fa-laptop
          %h4.text-capitalize User Experience
          %p
            We are obsessively focussed on the user experience of every project we are involved with. We take a wholistic view of user experience, considering all aspects of a user's interaction with the product, from acquisition to successful completion. It really is all about the user!
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.fa.fa-code
          %h4.text-capitalize Code
          %p
            Good software is hard to define. Designing and building simple, use- able, and attractive programs that are fast, efficient, readable and ac- cessible is not easy...it is essential! I develop standards compliant code that is written to be readable, under- standable, and maintainable. This is what good software is all about.
          %p
            Don’t settle for anything less.
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.fa.fa-cogs
          %h4.text-capitalize Product Strategy
          %p
            Bringing your product successfully to market requires more than 'management', it requires vision. Coordinating the various aspects of a successful launch can be daunting. We have brought several products to fruition. From conception, design, user testing, coding, marketing, distribution and support.
      / /col
/ end features section

app/views/pages/_features_section_bu.html.haml
%section.features-section.border-bottom
  .container
    .row
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.ion-iphone
          %h4.text-capitalize Fully Responsive
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.ion-ios-person-outline
          %h4.text-capitalize User Friendly
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.ion-ios-cog-outline
          %h4.text-capitalize Well Documented
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.
      / /col
      .col-md-6.col-lg-3.margin-b-30
        .feature-box-center.text-center
          %i.ion-key
          %h4.text-capitalize Easy & Customizable
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.
      / /col
/ end features section

app/views/pages/_home_section.html.haml
%section#home.dzsparallaxer.auto-init.dzsparallaxer---window-height.use-loading{"data-options" => "{  mode_scroll: 'normal' }", :style => "position: relative; height: 800px;"}
  .divimage.dzsparallaxer--target{"data-src" => "#{image_path('img/bg1.jpg')}", :style => "width: 100%; height: 130%; background-image: url()"}
    .hero-parallax
      .hero-inner
        .hero-content
          .container.text-center
            .row
              .col-md-10.offset-md-1
                .hero-static
                  %h1 We design and build software for customers who appreciate great solutions.

                  -# %p.lead
                  -#   Let's work together!
                  -# .buttons
                  -#   %a.btn.btn-xl.btn-primary.video-popup{:href => "https://www.youtube.com/watch?v=8zxj-6smeVA"}
                  -#     Video Tour
                  -#     %i.ion-play
                  -#   %a.btn.btn-xl.btn-white-border{:href => "#"} Sign Up Free
          / container
        / hero content
      / hero inner
    / parallax hero
  / parallax image div
/ intro section end

app/views/pages/_interested_section.html.haml
.cta-skin
  .container.text-center#get-in-touch
    %h2 Are you interested in working with Humble Daisy?
    = link_to('Get in touch', contact_path, class: 'btn btn-rounded btn-white-border{')

app/views/pages/_pricing_section.html.haml
%section.pricing-section
  .space-90
  .container
    .center-title
      %h2 Easy plans. Cancel anytime.
      %p All Plans Include a 14 day free trail
    .row
      .col-md-4.margin-b-30
        .price-box
          .price-header
            %h1 Free
            %h4 Basic Plan
          %ul.list-unstyled.price-features
            %li 5 Team Members
            %li 6 Month Support
            %li 10 Pages
            %li 1 Domain
            %li 25 GB Storage
          .price-footer
            %a.btn.btn-rounded.btn-dark-border{:href => "#"} Sign Up
      / /col
      .col-md-4.margin-b-30
        .price-box.best-plan
          .price-header
            %h1
              %span.dolor> $
              9.99
              %span.peroid /Month
            %h4 Pro Plan
          %ul.list-unstyled.price-features
            %li 15 Team Members
            %li 12 Month Support
            %li 30 Pages
            %li 5 Domain
            %li 100 GB Storage
          .price-footer
            %a.btn.btn-rounded.btn-white-border{:href => "#"} Sign Up
      / /col
      .col-md-4.margin-b-30
        .price-box
          .price-header
            %h1
              %span.dolor> $
              29.99
              %span.peroid /Month
            %h4 Gold Plan
          %ul.list-unstyled.price-features
            %li 25 Team Members
            %li 24/7 Support
            %li Unlimited Pages
            %li 10 Domain
            %li Unlimited Storage
          .price-footer
            %a.btn.btn-rounded.btn-dark-border{:href => "#"} Sign Up
      / /col
  .space-60
/ end pricing section

app/views/pages/_showcase_profcast.html.haml
%section.showcase-section#showcase-profcast
  .space-90
  .container
    .row.align-items-center
      .col-md-12
        = image_tag('projects/ProfCast_Masthead.png', class: ' img-fluid center-img', alt: 'ProfCast Lecture Capture Masthead')
      .col-md-5.margin-b-30
        %h3
          ProfCast - Lecture Capture
        %p
          ProfCast is a versatile, powerful, yet very simple to use tool for recording lectures including PowerPoint and/or Keynote slides for creating enhanced podcasts. ProfCast provides a low cost solution for recording and distributing lectures, special events, and presentations as podcasts.

        %p
          ProfCast offers an integrated workflow that makes creating, recording, and publishing podcasts easy. It's as simple as Launch, Load, and Lecture!
        .row
          .col-md-6
            = link_to('Learn More', 'http://www.profcast.com', target: '_blank', class: ' btn btn-lg btn-primary btn-rounded')
      .col-md-6.offset-md-1.margin-b-30
        = image_tag('projects/ProfCast_Flow.png', class: ' img-fluid center-img', alt: 'ProfCast Lecture Capture Masthead')
    .space-60
/ end showcase section

app/views/pages/_showcase_section.html.haml
%section.showcase-section#showcase-section
  .space-90
  .container
    .row.align-items-center
      .col-md-5.margin-b-30
        %h3
          SonicPics - Digital Story Telling for iOS
        %p SonicPics is a very easy to use tool for turning your images into custom slideshow movies that you can share with your friends online! SonicPics lets you add images from your iPhone's photo library or camera, arrange your photos, and then narrate the project to create an enhanced m4v video (complete with chapters).
        %p Take photos of your kids, special events, weddings, vacations, the new pet, or first day at camp and narrate them with SonicPics!
        .row
          .col-md-6
            %ul.list
              %li
                %i.ion-ios-arrow-thin-right>
                Lorem ipsum dolor
              %li
                %i.ion-ios-arrow-thin-right>
                Duis lacinia dolor quis
          .col-md-6
            %ul.list
              %li
                %i.ion-ios-arrow-thin-right>
                Lorem ipsum dolor
              %li
                %i.ion-ios-arrow-thin-right>
                Duis lacinia dolor
      .col-md-6.offset-md-1.margin-b-30
        %img.img-fluid.center-img{:alt => "", :src => "#{image_path('img/shot1.png')}"}/
    .space-60
/ end showcase section

app/views/pages/_showcase_sonicpics.html.haml
%section.showcase-section.bg-faded#showcase-sonicpics
  .space-90
  .container
    .row.align-items-center
      .col-md-5.offset-md-1.margin-b-30
        %img.img-fluid{:alt => "", :src => "#{image_path('img/iphone.png')}"}/
      .col-md-5.margin-b-30
        %h3
          SonicPics - Digital Story Telling for iOS
        %p.margin-b-20
          SonicPics is a very easy to use tool for turning your images into custom slideshow movies that you can share with your friends online! SonicPics lets you add images from your iPhone's photo library or camera, arrange your photos, and then narrate the project to create an enhanced m4v video (complete with chapters).
        %p.margin-b-20
          Take photos of your kids, special events, weddings, vacations, the new pet, or first day at camp and narrate them with SonicPics!
        = link_to('Learn More', 'http://www.sonicpics.com', target: '_blank', class: ' btn btn-lg btn-primary btn-rounded')
  .space-30
/ end showcase section

app/views/pages/_showcase_web.html.haml
%section.showcase-section#showcase-web
  .space-90
  .container
    .row.align-items-center
      .col-md-5.margin-b-30
        %h3
          Web Apps
        %p SonicPics is a very easy to use tool for turning your images into custom slideshow movies that you can share with your friends online! SonicPics lets you add images from your iPhone's photo library or camera, arrange your photos, and then narrate the project to create an enhanced m4v video (complete with chapters).
        %p Take photos of your kids, special events, weddings, vacations, the new pet, or first day at camp and narrate them with SonicPics!
        .row
          .col-md-6
            = link_to('Learn More', 'http://www.sonicpics.com', target: '_blank', class: ' btn btn-lg btn-primary btn-rounded')
      .col-md-6.offset-md-1.margin-b-30
        %img.img-fluid.center-img{:alt => "", :src => "#{image_path('img/shot1.png')}"}/
    .space-60
/ end showcase section

app/views/pages/_steps_section.html.haml
%section.steps#steps
  .space-90
  .container
    .center-title
      %h2 Easy to get started. 3 Step process.
      %p Take a look what the people think about our product
    .row
      .col-md-4.margin-b-30
        .step-box
          %h1 01
          %h4 Create Account.
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque efficitur turpis, vitae dictum dolor tristique in.
      .col-md-4.margin-b-30
        .step-box
          %h1 02
          %h4 Select Plan.
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque efficitur turpis, vitae dictum dolor tristique in.
      .col-md-4.margin-b-30
        .step-box
          %h1 03
          %h4 Assign Tasks.
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque efficitur turpis, vitae dictum dolor tristique in.
  .space-60
/ end steps

app/views/pages/_testimonials_section.html.haml
%section.testimonials.skin-bg#testamonials
  .space-90
  .container
    .center-title
      %h2 True words from our customers.
      %p Over 500,000 Customers worldwide
    .row
      .col-md-4.margin-b-30
        .feedback-box
          %p
            " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rhoncus magna a lacinia tempor. Fusce et turpis posuere, imperdiet orci et, tempus ex. Nunc vitae pellentesque ipsum. Quisque id magna a nisl vestibulum ullamcorper. "
        .testi-info
          %img.rounded-circle{:alt => "", :src => "#{image_path('img/avtar-1.jpg')}", :width => "60"}/
          .content
            %h4 Nikita Miller
            %em Saas Customer
      .col-md-4.margin-b-30
        .feedback-box
          %p
            " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rhoncus magna a lacinia tempor. Fusce et turpis posuere, imperdiet orci et, tempus ex. Nunc vitae pellentesque ipsum. Quisque id magna a nisl vestibulum ullamcorper. "
        .testi-info
          %img.rounded-circle{:alt => "", :src => "#{image_path('img/avtar-2.jpg')}", :width => "60"}/
          .content
            %h4 John Doe
            %em Saas Customer
      .col-md-4.margin-b-30
        .feedback-box
          %p
            " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rhoncus magna a lacinia tempor. Fusce et turpis posuere, imperdiet orci et, tempus ex. Nunc vitae pellentesque ipsum. Quisque id magna a nisl vestibulum ullamcorper. "
        .testi-info
          %img.rounded-circle{:alt => "", :src => "#{image_path('img/avtar-3.jpg')}", :width => "60"}/
          .content
            %h4 Emily Howkins
            %em Saas Customer
  .space-60
/ end testimonials section

app/views/pages/about.html.haml
.container#about
  %p
  Humble Daisy was founded in 2002 with the goal of providing simple and elegant solutions for those who appreciate such things. We seek people who understand the importance of putting their users first and work diligently to make user centered designs. Our designs facilitate success while expressing the unique qualities that make each of us special.
  %p
  To learn more about the name Humble Daisy, visit our
  = link_to "About Our Name", about_our_name_path
  page.
  %p
  To contact Humble Daisy Designs for you next web project, visit our
  = link_to "Contact Us", contact_path
  page.

app/views/pages/about_our_name.html.haml
.container.col-md-10#about_our_name

  %p
  The name Humble Daisy comes from the name of a song from one of our favorite bands, XTC. XTC has been with us since the late 1970's and has aged and mellowed well. They are intelligent, witty, philosophical and honorable. As a band they possess the simple elegance that humble daisy aspires to. Here are the lyrics to the original song by XTC.

  %p
  Humble Daisy - Andy Partridge, XTC

  %p
    Humble Daisy
    %br
    Form a chain to hold all battleships in check
    %br
    Humble Daisy
    %br
    Knit a ladder down to nature's sunken wreck
    %br
    Ragged rug unbound
    %br
    Tangle trip the lovers
    %br
    Royal barge aground
    %br
    Brighter than all of the others on the window sill
    %br
    I'll sing about you if nobody else will
    %br
    Humble Daisy
    %br
    Cast the milk and coins of morning's cash about
    %br
    Humble Daisy
    %br
    I fell down to heaven as you picked me out
    %br
    We'll look up together
    %br
    Browsing through some old sky
    %br
    Sipping in the weather
    %br
    You've got me dizzy, the fly that climbed the sugar hill
    %br
    I'll lay upon you 'till somebody else will
    %br
    Humble Daisy
    %br
    We'll look up together

    %hr

  %p
    When asked about the song "Humble Daisy" Andy Partridge responded; `A paean to the person and the weed. There's a wonderful field where I walk my dog and overnight these big daisies came up. So the song's in praise of that glorious weed. As for some of the words, I have no idea what they mean - but they're pictorially gorgeous.' This is from the writer of the song...

  %p
    I like the phrase "in praise of that glorious weed", especially for a small business. The lyrics to me are compelling. A tribute to a beautiful weed with the last line that says "We'll look up together..." I couldn't think of a better name for a company! David

  %p
    DAISY: The word Daisy comes from the Old English 'day's eye'. This implied that the flower opened in the morning and closed at night.

  %p
    The Daisy family or Compositae family is thought to be the largest genus with over 1200 species. It includes lots of popular garden plants like Chrysanthemums, Dahlias, Sunflowers, Asters and Calendulas (Marigolds).

  %p
    <a name="Paean"></a>pae&middot;an also pe&middot;an n.
    %br
    %ol
      %li
        A song of joyful praise or exultation.
      %li
        A fervent expression of joy or praise: "The art... was a paean to paganism" (Will Durant).
      %li
        An ancient Greek hymn of thanksgiving or invocation, especially to Apollo.
  %hr
  %p
    [Latin paen, hymn of thanksgiving, often addressed to Apollo, from Greek pain, from Pai, a title of Apollo.]

  %p
    To learn more about the name Humble Daisy, visit our
    = link_to('About Us', about_path)
    page.

app/views/pages/contact.html.haml
.container#contact
  .card-group
    .card
      -# %img.card-img-top{:alt => "Card image cap", :src => "#{image_path('img/avtar-3.jpg')}"}/
      .card-block
        %h4.card-title Humble Daisy, Inc
        %p.card-text
          %br 1342 Arella Blvd.
          %br Ann Arbor, MI 48103
          %br
            (734) 864-1232 -- Phone

          %p
            For general inquiries contact
            %br
              <a href="mailto:humbledaisy@humbledaisy.com" target="_blank">humbledaisy@humbledaisy.com</a>
            -# %a.btn.btn-primary{:href => "#"} Go somewhere


    .card
      -# %img.card-img-top{:alt => "Card image cap", :src => "#{image_path('img/avtar-3.jpg')}"}/
      .card-block
        %h4.card-title David Chmura
        %p.card-text
          %h4 Chief Instigator
          <a href="mailto:dschmura@humbledaisy.com" target="_blank">dschmura@humbledaisy.com</a>

        %br
        (734) 864-1232 -- Phone
        -# %a.btn.btn-primary{:href => "#"} Go somewhere

    .card
      -# %img.card-img-top{:alt => "Card image cap", :src => "#{image_path('img/avtar-3.jpg')}"}
      .card-block
        %h4.card-title Michael Chmura
        %p.card-text
          %h4 Usability Consultant
          <a href="mailto:mbchmura@humbledaisy.com" target="_blank">mbchmura@humbledaisy.com</a>

          %br (734) 864-1232 -- Phone
        -# %a.btn.btn-primary{:href => "#"} Go somewhere


.containers
  .space-90
  .row
    .col-lg-5.col-md-6.offset-1.margin-b-40
      %h3.margin-b-30 Feel free to contact us!
      = form_for @message, url: create_message_url do |f|
        = notice
        = @message.errors.full_messages.join(', ')
        .col-sm-12.margin-b-20
          = f.text_field :name, placeholder: 'Full Name...', class: 'form-control'
        .col-sm-12.margin-b-20
          = f.email_field :email, placeholder: 'Email Address...', class: 'form-control'
        .col-sm-12.margin-b-20
          = f.text_area :body, placeholder: 'Message...', class: 'form-control', rows: 5
        .row
          .col-sm-12.text-right
            = f.submit 'Send Message', class: ' btn btn-primary btn-rounded'
      -# %form{:action => "#", :method => "post"}
      -# .row
      -#   .col-sm-12
      -#     .row
      -#       .col-sm-12.margin-b-20
      -#         %input.form-control{:name => "name", :placeholder => "Full Name....", :type => "text"}/
      -#       .col-sm-12.margin-b-20
      -#         %input.form-control{:name => "email", :placeholder => "Email Address....", :type => "text"}/
      -#   .col-sm-12.margin-b-20
      -#     %textarea.form-control{:name => "message", :placeholder => "Message....", :rows => "5"}
      -#   .row
      -#     .col-sm-12.text-center
      -#       .data-status
      -#       / data submit status
      -#   .row
      -#     .col-sm-12.text-right
      -#       %button.btn.btn-primary.btn-rounded{:name => "submit", :type => "submit"} send message
    .col-lg-5.col-md-4.margin-b-40
      %h4 Address
      %p.margin-b-0
        1342 Arella Boulevard,
        %br
          Ann Arbor, MI
          %br
            48103
          %hr
            %h4 Phone
            %p.margin-b-0
              734-864-1232
              %hr
                %h4 Email  support center
                %p.margin-b-0
                  support@humbledaisy.com

                .space-50
  / Google Maps
  .google-map-container.margin-b-60
    #googlemaps{:style => "width: 100%;height: 400px;"}


      %script{:src => "https://maps.google.com/maps/api/js?key=AIzaSyBENlIxSKmTEK2fJeKjKo_JMxC9jE2IkL4"}

      :javascript
        (function ($) {
            $(document).on('turbolinks:load', function() {

                $('#googlemaps').gMap({
                    maptype: 'ROADMAP',
                    scrollwheel: false,
                    zoom: 13,
                    markers: [
                        {
                            address: 'Ann Arbor, MI', // Your Adress Here
                            html: 'We live and work in Ann Arbor, MI',
                            popup: false,
                            icon: {
                                image: "assets/images/marker.png",
                                iconsize: [48, 48],
                                iconanchor: [48, 48]
                            }
                        }
                    ]
                });
            });
        })(this.jQuery);